In [1]:
import torch
import numpy as np
from torch import nn
import matplotlib.pyplot as plt
weigth=0.7
bias=0.3
start=0
end=1
step=0.02
X=torch.arange(start,end,step).unsqueeze(dim=1)# unsequeeze is used to add extra diminsion 
Y=weigth*X+bias
print(X[:10],Y[:10])
train_split=int(0.8*len(X))
X_train,Y_train=X[:train_split],Y[:train_split]
X_test,Y_test=X[train_split:],Y[train_split:]

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800]]) tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260]])


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21908\1277022506.py:10: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  X=torch.arange(start,end,step).unsqueeze(dim=1)# unsequeeze is used to add extra diminsion


In [2]:
len(X_train),len(X_test)

(40, 10)

In [6]:
def plot(train_data=X_train,train_labels=Y_train,test_data=X_test,test_labels=Y_test,predictions=None):
    plt.figure(figsize=(10,7))
    plt.scatter(train_data,train_labels,c="b",s=4,label="Training data")
    plt.scatter(test_data,test_labels,c="b",s=4,label="Testing data")
    if predictions is not None:
        plt.scatter(test_data,predictions,c="r",s=4,label="Prediciton")
    plt.legend(prop={"size":14})
        

In [67]:
class linearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights=nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
        self.bias=nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
    def forward(self,x:torch.Tensor)->torch.Tensor:
        return self.weights * x + self.bias
        
        

In [68]:
model_0=linearRegression()

In [9]:
with torch.inference_mode():
    y_preds=model_0(X_test)
y_preds
    

tensor([[2.1461],
        [2.1597],
        [2.1733],
        [2.1869],
        [2.2005],
        [2.2142],
        [2.2278],
        [2.2414],
        [2.2550],
        [2.2686]])

In [11]:
y_preds=model_0(X_test)
y_preds

tensor([[2.1461],
        [2.1597],
        [2.1733],
        [2.1869],
        [2.2005],
        [2.2142],
        [2.2278],
        [2.2414],
        [2.2550],
        [2.2686]], grad_fn=<AddBackward0>)

In [69]:
loss_fn=nn.L1Loss()
optimizer=torch.optim.SGD(params=model_0.parameters(),lr=0.01)

In [71]:
torch.manual_seed(42)
epoch_count=[]
loss_values=[]
test_loss_values=[]
epochs=100
for epoch in range(epochs+1):
    model_0.train()
    y_pred=model_0(X_train)
    loss=loss_fn(y_pred,Y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    model_0.eval()
    with torch.inference_mode():
        test_pred=model_0(X_test)
        test_loss=loss_fn(test_pred,Y_test)
    if epoch % 10 == 0:
        epoch_count.append(epoch)
        loss_values.append(loss)
        test_loss_values.append(test_loss)
        print(f"{loss}")
        print(f"epoch:{epoch} | loss:{loss} | test loss :{test_loss}")
        print(model_0.state_dict())

0.024110013619065285
epoch:0 | loss:0.024110013619065285 | test loss :0.05536102131009102
OrderedDict([('weights', tensor([0.5818])), ('bias', tensor([0.3498]))])
0.020677709951996803
epoch:10 | loss:0.020677709951996803 | test loss :0.04777535796165466
OrderedDict([('weights', tensor([0.5988])), ('bias', tensor([0.3423]))])
0.017245199531316757
epoch:20 | loss:0.017245199531316757 | test loss :0.0395028181374073
OrderedDict([('weights', tensor([0.6159])), ('bias', tensor([0.3353]))])
0.013806397095322609
epoch:30 | loss:0.013806397095322609 | test loss :0.031230276450514793
OrderedDict([('weights', tensor([0.6331])), ('bias', tensor([0.3283]))])
0.010375778190791607
epoch:40 | loss:0.010375778190791607 | test loss :0.023644620552659035
OrderedDict([('weights', tensor([0.6501])), ('bias', tensor([0.3208]))])
0.006941580679267645
epoch:50 | loss:0.006941580679267645 | test loss :0.0153720797970891
OrderedDict([('weights', tensor([0.6672])), ('bias', tensor([0.3138]))])
0.003502774983644